// admin-dashboard/src/app/shared/components/confirmation-modal/confirmation-modal.component.ts
import { Component, output, input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule, Trash2, Info, TriangleAlert } from 'lucide-angular';

@Component({
  selector: 'app-confirmation-modal',
  standalone: true,
  imports: [CommonModule, LucideAngularModule],
  templateUrl: './confirmation-modal.component.html',
})
export class ConfirmationModalComponent {
  isOpen = input<boolean>(false);
  title = input<string>('Confirm Action');
  message = input<string>('Are you sure you want to proceed?');
  type = input<'danger' | 'warning' | 'info'>('danger');
  confirmText = input<string>('Confirm');
  cancelText = input<string>('Cancel');
  confirmed = output<void>();
  cancelled = output<void>();

  readonly Trash2Icon = Trash2;
  readonly AlertTriangleIcon = TriangleAlert;
  readonly InfoIcon = Info;

  onConfirm() {
    this.confirmed.emit();
  }

  onCancel() {
    this.cancelled.emit();
  }
}

@if (isOpen()) {
<div class="fixed inset-0 z-115 flex items-center justify-center p-4">
  <div
    class="absolute inset-0 backdrop-blur-sm bg-opacity-50 transition-opacity"
    (click)="onCancel()"
  ></div>

  <div
    class="relative bg-white rounded-2xl shadow-2xl w-full max-w-md transform transition-all"
  >
    <div class="flex justify-center pt-8 pb-4">
      <div
        class="w-16 h-16 rounded-full flex items-center justify-center"
        [ngClass]="{
          'bg-red-100': type() === 'danger',
          'bg-yellow-100': type() === 'warning',
          'bg-blue-100': type() === 'info'
        }"
      >
        @if (type() === 'danger') {
        <lucide-icon
          [img]="Trash2Icon"
          [size]="32"
          class="text-red-600"
        ></lucide-icon>
        } @else if (type() === 'warning') {
        <lucide-icon
          [img]="AlertTriangleIcon"
          [size]="32"
          class="text-yellow-600"
        ></lucide-icon>
        } @else {
        <lucide-icon
          [img]="InfoIcon"
          [size]="32"
          class="text-blue-600"
        ></lucide-icon>
        }
      </div>
    </div>

    <div class="px-8 pb-6 text-center">
      <h3 class="text-xl font-bold text-gray-900 mb-2">
        {{ title() }}
      </h3>
      <p class="text-gray-600">
        {{ message() }}
      </p>
    </div>

    <div class="flex gap-3 px-8 pb-8">
      <button
        type="button"
        (click)="onCancel()"
        class="flex-1 py-3 cursor-pointer px-4 bg-gray-100 text-gray-700 font-semibold rounded-lg hover:bg-gray-200 transition-colors"
      >
        {{ cancelText() }}
      </button>
      <button
        type="button"
        (click)="onConfirm()"
        class="flex-1 py-3 px-4 cursor-pointer font-semibold rounded-lg transition-all shadow-md hover:shadow-lg"
        [ngClass]="{
          'bg-red-600 hover:bg-red-700 text-white': type() === 'danger',
          'bg-yellow-600 hover:bg-yellow-700 text-white': type() === 'warning',
          'bg-blue-600 hover:bg-blue-700 text-white': type() === 'info'
        }"
      >
        {{ confirmText() }}
      </button>
    </div>
  </div>
</div>
}

// transport/src/components/(shared)/ConfirmationModal.tsx
"use client";

import { Dialog, DialogPanel, DialogTitle } from "@headlessui/react";
import { AlertTriangle } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

interface ConfirmationModalProps {
  isOpen: boolean;
  onClose: () => void;
  onConfirm: () => void;
  title?: string;
  message: string;
  confirmText?: string;
  cancelText?: string;
  type?: "danger" | "warning" | "info";
}

export default function ConfirmationModal({
  isOpen,
  onClose,
  onConfirm,
  title = "Confirm Action",
  message,
  confirmText = "Confirm",
  cancelText = "Cancel",
  type = "warning"
}: ConfirmationModalProps) {
  const typeColors = {
    danger: "bg-red-500 hover:bg-red-600",
    warning: "bg-yellow-500 hover:bg-yellow-600",
    info: "bg-blue-500 hover:bg-blue-600"
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <Dialog as="div" open={isOpen} onClose={onClose} className="relative z-9999">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black bg-opacity-50"
          />

          <div className="fixed inset-0 overflow-y-auto">
            <div className="flex min-h-full items-center justify-center p-4">
              <DialogPanel
                as={motion.div}
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.95 }}
                className="w-full max-w-md bg-white rounded-lg shadow-xl p-6"
              >
                <div className="flex items-center gap-4 mb-4">
                  <div className={`p-3 rounded-full ${type === "danger" ? "bg-red-100" : type === "warning" ? "bg-yellow-100" : "bg-blue-100"}`}>
                    <AlertTriangle className={`w-6 h-6 ${type === "danger" ? "text-red-600" : type === "warning" ? "text-yellow-600" : "text-blue-600"}`} />
                  </div>
                  <DialogTitle className="text-xl font-semibold text-gray-900">
                    {title}
                  </DialogTitle>
                </div>
                
                <p className="text-gray-600 mb-6">{message}</p>

                <div className="flex gap-3 justify-end">
                  <button
                    onClick={onClose}
                    className="px-4 py-2 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 transition-colors"
                  >
                    {cancelText}
                  </button>
                  <button
                    onClick={() => {
                      onConfirm();
                      onClose();
                    }}
                    className={`px-4 py-2 text-white rounded-lg transition-colors ${typeColors[type]}`}
                  >
                    {confirmText}
                  </button>
                </div>
              </DialogPanel>
            </div>
          </div>
        </Dialog>
      )}
    </AnimatePresence>
  );
}
